TARGET = harbour-plexfreq
VERSION = 0.1.0
CONFIG += sailfishapp c++11
CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-1.0 gstreamer-app-1.0 gio-2.0
DEFINES += SAILFISH
SOURCES += src/main.cpp src/backend.cpp src/i18n.cpp
HEADERS += src/backend.h src/plexfreq_core.h src/i18n.h
RESOURCES += translations.qrc icons.qrc
catalogues.files = translations/*.qm
catalogues.path = /usr/share/harbour-plexfreq/translations
INSTALLS += catalogues
LIBS += $$PWD/thirdparty/libplexfreq_core.a -lpthread -ldl -lm
LIBS += -lsailfishapp -lmdeclarativecache5
QMAKE_LFLAGS += -pie
PRE_TARGETDEPS += $$PWD/thirdparty/libplexfreq_core.a
DISTFILES += harbour-plexfreq.desktop rpm/harbour-plexfreq.spec qml/harbour-plexfreq.qml qml/pages/*.qml qml/shared/*.qml
launchericon.files = icons/172x172/harbour-plexfreq.png
launchericon.path = /usr/share/icons/hicolor/172x172/apps
INSTALLS += launchericon
